name: Express Testing

on:
  push:
    branches: [main]

jobs:
  jesttesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true